export interface Activity {
  _id: string;
  name: string;
}

export interface Section {
  _id: string;
  name: string;
  activities: Activity[];
}

export const sections: Section[] = [
  {
    _id: 'movies',
    name: 'Movies',
    activities: [
      { _id: '1', name: 'Inception' },
      { _id: '2', name: 'The Matrix' },
      { _id: '3', name: 'The Shawshank Redemption' },
      { _id: '4', name: 'The Godfather' },
      { _id: '5', name: 'Pulp Fiction' },
      { _id: '6', name: 'The Dark Knight' },
      { _id: '7', name: 'Fight Club' },
      { _id: '8', name: 'Forrest Gump' },
      { _id: '9', name: 'Interstellar' },
      { _id: '10', name: 'Parasite' },
      { _id: '11', name: 'The Lord of the Rings: The Return of the King' },
      { _id: '12', name: 'The Empire Strikes Back' },
      { _id: '13', name: 'The Lion King' },
      { _id: '14', name: 'Back to the Future' },
      { _id: '15', name: 'Gladiator' },
      { _id: '16', name: 'Jurassic Park' },
      { _id: '17', name: 'The Silence of the Lambs' },
      { _id: '18', name: 'Schindler’s List' },
      { _id: '19', name: 'The Green Mile' },
      { _id: '20', name: 'Saving Private Ryan' },
      { _id: '21', name: 'The Prestige' },
      { _id: '22', name: 'The Departed' },
      { _id: '23', name: 'Whiplash' },
      { _id: '24', name: 'The Intouchables' },
      { _id: '25', name: 'The Pianist' },
      { _id: '26', name: 'The Usual Suspects' },
      { _id: '27', name: 'Se7en' },
      { _id: '28', name: 'The Sixth Sense' },
      { _id: '29', name: 'The Green Book' },
      { _id: '30', name: 'The Grand Budapest Hotel' },
      { _id: '31', name: 'The Social Network' },
      { _id: '32', name: 'The Wolf of Wall Street' },
      { _id: '33', name: 'The Revenant' },
      { _id: '34', name: 'Mad Max: Fury Road' },
      { _id: '35', name: 'Django Unchained' },
      { _id: '36', name: 'The Hateful Eight' },
      { _id: '37', name: 'Inglourious Basterds' },
      { _id: '38', name: 'The Big Lebowski' },
      { _id: '39', name: 'The Truman Show' },
      { _id: '40', name: 'The Shining' },
      { _id: '41', name: 'A Clockwork Orange' },
      { _id: '42', name: 'Blade Runner' },
      { _id: '43', name: 'Alien' },
      { _id: '44', name: 'Apocalypse Now' },
      { _id: '45', name: 'Full Metal Jacket' },
      { _id: '46', name: 'The Godfather Part II' },
      { _id: '47', name: 'Goodfellas' },
      { _id: '48', name: 'Scarface' },
      { _id: '49', name: 'Taxi Driver' },
      { _id: '50', name: 'Raging Bull' },
      { _id: '51', name: 'The Irishman' },
      { _id: '52', name: 'Once Upon a Time in America' },
      { _id: '53', name: 'Heat' },
      { _id: '54', name: 'Casino' },
      { _id: '55', name: 'The Untouchables' },
      { _id: '56', name: 'The Departed' },
      { _id: '57', name: 'The Aviator' },
      { _id: '58', name: 'Catch Me If You Can' },
      { _id: '59', name: 'The Terminal' },
      { _id: '60', name: 'Bridge of Spies' },
      { _id: '61', name: 'War Horse' },
      { _id: '62', name: 'Lincoln' },
      { _id: '63', name: 'Munich' },
      { _id: '64', name: 'Minority Report' },
      { _id: '65', name: 'A.I. Artificial Intelligence' },
      { _id: '66', name: 'Saving Private Ryan' },
      { _id: '67', name: 'Schindler’s List' },
      { _id: '68', name: 'Jurassic Park' },
      { _id: '69', name: 'E.T. the Extra-Terrestrial' },
      { _id: '70', name: 'Raiders of the Lost Ark' },
      { _id: '71', name: 'Jaws' },
      { _id: '72', name: 'Close Encounters of the Third Kind' },
      { _id: '73', name: 'The Color Purple' },
      { _id: '74', name: 'Empire of the Sun' },
      { _id: '75', name: 'Amistad' },
      { _id: '76', name: 'The Post' },
      { _id: '77', name: 'Ready Player One' },
      { _id: '78', name: 'The BFG' },
      { _id: '79', name: 'War of the Worlds' },
      { _id: '80', name: 'Catch Me If You Can' },
      { _id: '81', name: 'The Terminal' },
      { _id: '82', name: 'Minority Report' },
      { _id: '83', name: 'A.I. Artificial Intelligence' },
      { _id: '84', name: 'Saving Private Ryan' },
      { _id: '85', name: 'Schindler’s List' },
      { _id: '86', name: 'Jurassic Park' },
      { _id: '87', name: 'E.T. the Extra-Terrestrial' },
      { _id: '88', name: 'Raiders of the Lost Ark' },
      { _id: '89', name: 'Jaws' },
      { _id: '90', name: 'Close Encounters of the Third Kind' },
      { _id: '91', name: 'The Color Purple' },
      { _id: '92', name: 'Empire of the Sun' },
      { _id: '93', name: 'Amistad' },
      { _id: '94', name: 'The Post' },
      { _id: '95', name: 'Ready Player One' },
      { _id: '96', name: 'The BFG' },
      { _id: '97', name: 'War of the Worlds' },
      { _id: '98', name: 'Catch Me If You Can' },
      { _id: '99', name: 'The Terminal' },
      { _id: '100', name: 'Minority Report' },
    ],
  },
  {
    _id: 'documentaries',
    name: 'Documentaries',
    activities: [
      { _id: '1', name: 'The Last Dance (2020)' },
      { _id: '2', name: 'Making a Murderer (2015)' },
      { _id: '3', name: 'Planet Earth II (2016)' },
      { _id: '4', name: '13th (2016)' },
      { _id: '5', name: 'Blackfish (2013)' },
      { _id: '6', name: 'Won’t You Be My Neighbor? (2018)' },
      { _id: '7', name: 'The Social Dilemma (2020)' },
      { _id: '8', name: 'Free Solo (2018)' },
      { _id: '9', name: 'Inside Job (2010)' },
      { _id: '10', name: 'Jiro Dreams of Sushi (2011)' },
      { _id: '11', name: 'Cowspiracy (2014)' },
      { _id: '12', name: 'Life on Our Planet (2023)' },
      { _id: '13', name: 'American Factory (2019)' },
      { _id: '14', name: 'Won’t You Be My Neighbor? (2018)' },
      { _id: '15', name: 'Apollo 11 (2019)' },
      { _id: '16', name: 'Virunga (2014)' },
      { _id: '17', name: 'The Cove (2009)' },
      { _id: '18', name: 'David Attenborough: A Life on Our Planet (2020)' },
      { _id: '19', name: 'Bowling for Columbine (2002)' },
      { _id: '20', name: 'Fahrenheit 9/11 (2004)' },
      { _id: '21', name: 'The Act of Killing (2012)' },
      { _id: '22', name: '20 Feet from Stardom (2013)' },
      { _id: '23', name: 'Man on Wire (2008)' },
      { _id: '24', name: 'Icarus (2017)' },
      { _id: '25', name: 'The Fog of War (2003)' },
      { _id: '26', name: 'Searching for Sugar Man (2012)' },
      { _id: '27', name: 'An Inconvenient Truth (2006)' },
      { _id: '28', name: 'Food, Inc. (2008)' },
      { _id: '29', name: 'Super Size Me (2004)' },
      {
        _id: '30',
        name: 'Hearts of Darkness: A Filmmaker’s Apocalypse (1991)',
      },
    ],
  },
  {
    _id: 'serials',
    name: 'Serials',
    activities: [
      { _id: '1', name: 'Breaking Bad' },
      { _id: '2', name: 'Game of Thrones' },
      { _id: '3', name: 'Stranger Things' },
      { _id: '4', name: 'The Crown' },
      { _id: '5', name: 'The Office' },
      { _id: '6', name: 'Narcos' },
      { _id: '7', name: 'Friends' },
      { _id: '8', name: 'Money Heist (La Casa de Papel)' },
      { _id: '9', name: 'The Mandalorian' },
      { _id: '10', name: 'Dark' },
      { _id: '11', name: 'Peaky Blinders' },
      { _id: '12', name: 'The Witcher' },
      { _id: '13', name: 'The Walking Dead' },
      { _id: '14', name: 'The Boys' },
      { _id: '15', name: 'Better Call Saul' },
      { _id: '16', name: 'The Haunting of Hill House' },
      { _id: '17', name: 'Big Bang Theory' },
      { _id: '18', name: 'Fargo' },
      { _id: '19', name: 'Sherlock' },
      { _id: '20', name: 'Westworld' },
      { _id: '21', name: 'Mindhunter' },
      { _id: '22', name: 'Black Mirror' },
      { _id: '23', name: 'The Mandalorian' },
      { _id: '24', name: 'How I Met Your Mother' },
      { _id: '25', name: 'True Detective' },
      { _id: '26', name: 'Chernobyl' },
      { _id: '27', name: 'Narcos: Mexico' },
      { _id: '28', name: 'Vikings' },
      { _id: '29', name: 'Sons of Anarchy' },
      { _id: '30', name: 'The Boys' },
      { _id: '31', name: 'Hannibal' },
      { _id: '32', name: 'Stranger Things 2' },
      { _id: '33', name: 'Ozark' },
      { _id: '34', name: 'Lucifer' },
      { _id: '35', name: 'The Good Place' },
      { _id: '36', name: 'The Umbrella Academy' },
      { _id: '37', name: 'Dexter' },
      { _id: '38', name: 'The Expanse' },
      { _id: '39', name: 'The Handmaid’s Tale' },
      { _id: '40', name: 'GLOW' },
      { _id: '41', name: 'Killing Eve' },
      { _id: '42', name: 'The 100' },
      { _id: '43', name: 'The Flash' },
      { _id: '44', name: 'Black Sails' },
      { _id: '45', name: 'The Night Manager' },
      { _id: '46', name: 'The Marvelous Mrs. Maisel' },
      { _id: '47', name: 'Castle Rock' },
      { _id: '48', name: 'Narcos: Mexico' },
      { _id: '49', name: 'The Outsider' },
      { _id: '50', name: 'The Last of Us' },
      { _id: '51', name: 'The Boys: Diabolical' },
      { _id: '52', name: 'Rick and Morty' },
      { _id: '53', name: 'The Flash' },
      { _id: '54', name: 'Lovecraft Country' },
      { _id: '55', name: 'Cursed' },
      { _id: '56', name: 'The Dark Crystal: Age of Resistance' },
      { _id: '57', name: 'The Strain' },
      { _id: '58', name: 'The Orville' },
      { _id: '59', name: 'Snowpiercer' },
      { _id: '60', name: 'The Handmaid’s Tale' },
    ],
  },
  {
    _id: 'animated_movies',
    name: 'Animated movies',
    activities: [
      { _id: '1', name: 'Король Лев (The Lion King)' },
      { _id: '2', name: 'Шрек (Shrek)' },
      { _id: '3', name: 'История игрушек (Toy Story)' },
      { _id: '4', name: 'Холодное сердце (Frozen)' },
      { _id: '5', name: 'Вверх (Up)' },
      { _id: '6', name: 'Тайна Келлс (The Secret of Kells)' },
      { _id: '7', name: 'Рататуй (Ratatouille)' },
      { _id: '8', name: 'Кунг-фу панда (Kung Fu Panda)' },
      { _id: '9', name: 'Зверополис (Zootopia)' },
      { _id: '10', name: 'Как приручить дракона (How to Train Your Dragon)' },
      { _id: '11', name: 'Душа (Soul)' },
      { _id: '12', name: 'Лило и Стич (Lilo & Stitch)' },
      { _id: '13', name: 'Город героев (Big Hero 6)' },
      { _id: '14', name: 'Моана (Moana)' },
      { _id: '15', name: 'Храбрая сердцем (Brave)' },
      { _id: '16', name: 'Монстры на каникулах (Hotel Transylvania)' },
      { _id: '17', name: 'Смешарики' },
      {
        _id: '18',
        name: 'Приключения кота в сапогах (Puss in Boots: The Last Wish)',
      },
      {
        _id: '19',
        name: 'Спайдер-мен: Через вселенные (Spider-Man: Into the Spider-Verse)',
      },
      { _id: '20', name: 'Семейка Аддамс (The Addams Family)' },
      { _id: '21', name: 'Книга джунглей (The Jungle Book)' },
      { _id: '22', name: 'Алладин (Aladdin)' },
      { _id: '23', name: 'Красавица и чудовище (Beauty and the Beast)' },
      { _id: '24', name: 'Мулан (Mulan)' },
      { _id: '25', name: 'Дамбо (Dumbo)' },
      { _id: '26', name: 'Симпсоны в кино (The Simpsons Movie)' },
      { _id: '27', name: 'Гадкий я (Despicable Me)' },
      {
        _id: '28',
        name: 'Тайная жизнь домашних животных (The Secret Life of Pets)',
      },
      { _id: '29', name: 'Мадагаскар (Madagascar)' },
      { _id: '30', name: 'Ледниковый период (Ice Age)' },
      { _id: '31', name: 'Фердинанд (Ferdinand)' },
      { _id: '32', name: 'Энканто (Encanto)' },
      { _id: '33', name: 'Волшебное приключение (Onward)' },
      {
        _id: '34',
        name: 'Губка Боб в бегах (The SpongeBob Movie: Sponge on the Run)',
      },
      { _id: '35', name: 'Скуби-Ду! (Scoob!)' },
      { _id: '36', name: 'Шпионский мост (Spies in Disguise)' },
      { _id: '37', name: 'Чудо-парк (Wonder Park)' },
      { _id: '38', name: 'Легенда о волках (Wolfwalkers)' },
      { _id: '39', name: 'Балто (Balto)' },
      { _id: '40', name: 'Аннабель (Annabelle’s Wish)' },
      {
        _id: '41',
        name: 'Покемон: Детектив Пикачу (Pokémon Detective Pikachu)',
      },
      { _id: '42', name: 'Секреты Коко (Coco)' },
      { _id: '43', name: 'Где дракон? (Where’s the Dragon?)' },
      { _id: '44', name: 'Золушка (Cinderella)' },
      { _id: '45', name: 'Принц Египта (The Prince of Egypt)' },
      { _id: '46', name: 'Валли (WALL-E)' },
      { _id: '47', name: 'Тачки (Cars)' },
      { _id: '48', name: 'Искатели приключений (Treasure Planet)' },
      {
        _id: '49',
        name: 'Атлантида: Затерянный мир (Atlantis: The Lost Empire)',
      },
      { _id: '50', name: 'Корпорация монстров (Monsters, Inc.)' },
      { _id: '51', name: 'Душевная кухня (Soul Kitchen)' },
      { _id: '52', name: 'Чудеса науки (Meet the Robinsons)' },
      { _id: '53', name: 'Фиксики' },
      { _id: '54', name: 'Смешарики. Дежавю' },
      { _id: '55', name: 'Эггси из королевской службы (Kingsman)' },
      { _id: '56', name: 'Кролик Питер (Peter Rabbit)' },
      { _id: '57', name: 'Алиса в стране чудес (Alice in Wonderland)' },
      { _id: '58', name: 'Волшебный мир (Fantasia)' },
      { _id: '59', name: 'Черепашки-ниндзя (TMNT)' },
      { _id: '60', name: 'Муми-тролли' },
    ],
  },
  {
    _id: 'anime',
    name: 'Anime',
    activities: [
      { _id: '101', name: 'Attack on Titan' },
      { _id: '102', name: 'Naruto' },
      { _id: '103', name: 'One Piece' },
      { _id: '104', name: 'Death Note' },
      { _id: '105', name: 'Fullmetal Alchemist: Brotherhood' },
      { _id: '106', name: 'My Hero Academia' },
      { _id: '107', name: 'Demon Slayer' },
      { _id: '108', name: 'Dragon Ball Z' },
      { _id: '109', name: 'Cowboy Bebop' },
      { _id: '110', name: 'Spirited Away' },
      { _id: '111', name: 'Neon Genesis Evangelion' },
      { _id: '112', name: 'Sword Art Online' },
      { _id: '113', name: 'Tokyo Ghoul' },
      { _id: '114', name: 'Bleach' },
      { _id: '115', name: 'Fairy Tail' },
      { _id: '116', name: 'Hunter x Hunter' },
      { _id: '117', name: 'One Punch Man' },
      { _id: '118', name: "JoJo's Bizarre Adventure" },
      { _id: '119', name: 'Code Geass' },
      { _id: '120', name: 'Steins;Gate' },
      { _id: '121', name: 'Your Lie in April' },
      { _id: '122', name: 'Clannad' },
      { _id: '123', name: 'Fate/Stay Night' },
      { _id: '124', name: 'Black Clover' },
      { _id: '125', name: 'Re:Zero' },
      { _id: '126', name: 'Mob Psycho 100' },
      { _id: '127', name: 'The Seven Deadly Sins' },
      { _id: '128', name: 'Gintama' },
      { _id: '129', name: 'Akame ga Kill!' },
      { _id: '130', name: 'No Game No Life' },
      { _id: '131', name: 'Overlord' },
      { _id: '132', name: 'KonoSuba' },
      { _id: '133', name: 'Toradora!' },
      { _id: '134', name: 'Angel Beats!' },
      { _id: '135', name: 'Anohana' },
      { _id: '136', name: 'Made in Abyss' },
      { _id: '137', name: 'The Promised Neverland' },
      { _id: '138', name: 'Dr. Stone' },
      { _id: '139', name: 'Beastars' },
      { _id: '140', name: 'Vinland Saga' },
      { _id: '141', name: 'The Rising of the Shield Hero' },
      { _id: '142', name: 'Goblin Slayer' },
      { _id: '143', name: 'Berserk' },
      { _id: '144', name: 'Hellsing' },
      { _id: '145', name: 'Trigun' },
      { _id: '146', name: 'Samurai Champloo' },
      { _id: '147', name: 'FLCL' },
      { _id: '148', name: 'Paranoia Agent' },
      { _id: '149', name: 'Serial Experiments Lain' },
      { _id: '150', name: 'Ghost in the Shell' },
      { _id: '151', name: 'Akira' },
      { _id: '152', name: 'Princess Mononoke' },
      { _id: '153', name: "Howl's Moving Castle" },
      { _id: '154', name: 'Castle in the Sky' },
      { _id: '155', name: 'Nausicaä of the Valley of the Wind' },
      { _id: '156', name: "Kiki's Delivery Service" },
      { _id: '157', name: 'My Neighbor Totoro' },
      { _id: '158', name: 'Ponyo' },
      { _id: '159', name: 'The Wind Rises' },
      { _id: '160', name: 'The Tale of the Princess Kaguya' },
      { _id: '161', name: 'When Marnie Was There' },
      { _id: '162', name: 'The Secret World of Arrietty' },
      { _id: '163', name: 'The Cat Returns' },
      { _id: '164', name: 'Whisper of the Heart' },
      { _id: '165', name: 'The Boy and the Beast' },
      { _id: '166', name: 'Summer Wars' },
      { _id: '167', name: 'Wolf Children' },
      { _id: '168', name: 'The Girl Who Leapt Through Time' },
      { _id: '169', name: 'Paprika' },
      { _id: '170', name: 'Perfect Blue' },
      { _id: '171', name: 'Redline' },
      { _id: '172', name: 'Tekkonkinkreet' },
      { _id: '173', name: '5 Centimeters per Second' },
      { _id: '174', name: 'Garden of Words' },
      { _id: '175', name: 'Your Name' },
      { _id: '176', name: 'Weathering with You' },
      { _id: '177', name: 'A Silent Voice' },
      { _id: '178', name: 'I Want to Eat Your Pancreas' },
      { _id: '179', name: 'The Anthem of the Heart' },
      { _id: '180', name: 'The Garden of Sinners' },
      { _id: '181', name: 'Fate/Zero' },
      { _id: '182', name: 'Fate/Apocrypha' },
      { _id: '183', name: 'Fate/Grand Order' },
      { _id: '184', name: 'Fate/Extra Last Encore' },
      { _id: '185', name: 'Fate/kaleid liner Prisma☆Illya' },
      { _id: '186', name: 'Fate/stay night: Unlimited Blade Works' },
      { _id: '187', name: "Fate/stay night: Heaven's Feel" },
      { _id: '188', name: 'Fate/Prototype' },
      { _id: '189', name: 'Fate/strange Fake' },
      { _id: '190', name: 'Fate/Grand Order: Camelot' },
      { _id: '191', name: 'Fate/Grand Order: Babylonia' },
      { _id: '192', name: 'Fate/Grand Order: Solomon' },
      { _id: '193', name: 'Fate/Grand Order: Moonlight/Lostroom' },
      { _id: '194', name: 'Fate/Grand Order: First Order' },
      { _id: '195', name: 'Fate/Grand Order: Zettai Majuu Sensen Babylonia' },
      { _id: '196', name: 'Fate/Grand Order: Shinsei Entaku Ryouiki Camelot' },
      { _id: '197', name: 'Fate/Grand Order: Kyoukai no Kanata' },
      {
        _id: '198',
        name: "Fate/Grand Order: Kyoukai no Kanata - I'll Be Here",
      },
      { _id: '199', name: 'Fate/Grand Order: Kyoukai no Kanata - Mirai-hen' },
      { _id: '200', name: 'Fate/Grand Order: Kyoukai no Kanata - Kako-hen' },
    ],
  },
  {
    _id: 'manga',
    name: 'Manga',
    activities: [
      { _id: '1', name: 'One Piece' },
      { _id: '2', name: 'Naruto' },
      { _id: '3', name: 'Attack on Titan (Shingeki no Kyojin)' },
      { _id: '4', name: 'Dragon Ball' },
      { _id: '5', name: 'Fullmetal Alchemist' },
      { _id: '6', name: 'My Hero Academia (Boku no Hero Academia)' },
      { _id: '7', name: 'Death Note' },
      { _id: '8', name: 'Bleach' },
      { _id: '9', name: 'Hunter x Hunter' },
      { _id: '10', name: 'Tokyo Ghoul' },
      { _id: '11', name: 'Demon Slayer (Kimetsu no Yaiba)' },
      { _id: '12', name: 'One Punch Man' },
      { _id: '13', name: 'Jujutsu Kaisen' },
      { _id: '14', name: 'Attack on Titan (Shingeki no Kyojin)' },
      { _id: '15', name: 'Black Clover' },
      { _id: '16', name: 'The Promised Neverland' },
      { _id: '17', name: 'Tokyo Revengers' },
      { _id: '18', name: 'Hunter x Hunter' },
      { _id: '19', name: 'Fairy Tail' },
      { _id: '20', name: 'JoJo’s Bizarre Adventure' },
      { _id: '21', name: 'Sword Art Online' },
      { _id: '22', name: 'One Punch Man' },
      { _id: '23', name: 'Neon Genesis Evangelion' },
      { _id: '24', name: 'Steins;Gate' },
      { _id: '25', name: 'Kaguya-sama: Love is War' },
      { _id: '26', name: 'Your Name (Kimi no Na wa)' },
      { _id: '27', name: 'Mob Psycho 100' },
      { _id: '28', name: 'Black Lagoon' },
      { _id: '29', name: 'Bleach' },
      { _id: '30', name: 'Akira' },
      { _id: '31', name: 'Slam Dunk' },
      { _id: '32', name: 'Gintama' },
      { _id: '33', name: 'Fruits Basket' },
      { _id: '34', name: 'Attack on Titan: No Regrets' },
      { _id: '35', name: 'Kuroko no Basket' },
      { _id: '36', name: 'Mushoku Tensei' },
      { _id: '37', name: 'Black Bullet' },
      { _id: '38', name: 'Vagabond' },
      { _id: '39', name: 'Hunter x Hunter: Greed Island' },
      { _id: '40', name: 'Nodame Cantabile' },
      { _id: '41', name: 'The Ancient Magus’ Bride' },
      { _id: '42', name: 'Fate/Stay Night' },
      { _id: '43', name: 'Re:Zero' },
      { _id: '44', name: 'Toradora!' },
      { _id: '45', name: 'Naruto: Shippuden' },
      { _id: '46', name: 'One Piece: Enies Lobby' },
      { _id: '47', name: 'Yona of the Dawn' },
      { _id: '48', name: 'Clover' },
      { _id: '49', name: 'Black Clover: Asta’s Origin' },
      { _id: '50', name: 'Vinland Saga' },
      { _id: '51', name: 'Blue Lock' },
      { _id: '52', name: 'Kingdom' },
      { _id: '53', name: 'Hunter x Hunter: Chimera Ant arc' },
      { _id: '54', name: 'The Seven Deadly Sins' },
      { _id: '55', name: 'Bleach: Thousand-Year Blood War' },
      { _id: '56', name: 'Saint Seiya' },
      { _id: '57', name: 'Naruto: The Last' },
      { _id: '58', name: 'Attack on Titan: Final Season' },
      { _id: '59', name: 'Magi: The Labyrinth of Magic' },
      { _id: '60', name: 'Great Teacher Onizuka' },
    ],
  },
  {
    _id: 'books',
    name: 'Books',
    activities: [
      { _id: '201', name: '1984 by George Orwell' },
      { _id: '202', name: 'To Kill a Mockingbird by Harper Lee' },
      { _id: '203', name: 'The Great Gatsby by F. Scott Fitzgerald' },
      { _id: '204', name: 'Moby Dick by Herman Melville' },
      { _id: '205', name: 'War and Peace by Leo Tolstoy' },
      { _id: '206', name: 'Pride and Prejudice by Jane Austen' },
      { _id: '207', name: 'The Catcher in the Rye by J.D. Salinger' },
      { _id: '208', name: 'The Hobbit by J.R.R. Tolkien' },
      { _id: '209', name: 'Brave New World by Aldous Huxley' },
      { _id: '210', name: 'The Lord of the Rings by J.R.R. Tolkien' },
      { _id: '211', name: 'The Chronicles of Narnia by C.S. Lewis' },
      { _id: '212', name: 'Animal Farm by George Orwell' },
      { _id: '213', name: 'The Grapes of Wrath by John Steinbeck' },
      { _id: '214', name: 'Jane Eyre by Charlotte Brontë' },
      { _id: '215', name: 'Wuthering Heights by Emily Brontë' },
      { _id: '216', name: 'The Picture of Dorian Gray by Oscar Wilde' },
      { _id: '217', name: 'Crime and Punishment by Fyodor Dostoevsky' },
      { _id: '218', name: 'The Brothers Karamazov by Fyodor Dostoevsky' },
      { _id: '219', name: 'Anna Karenina by Leo Tolstoy' },
      { _id: '220', name: 'The Adventures of Huckleberry Finn by Mark Twain' },
      { _id: '221', name: 'The Adventures of Tom Sawyer by Mark Twain' },
      { _id: '222', name: 'Les Misérables by Victor Hugo' },
      { _id: '223', name: 'The Count of Monte Cristo by Alexandre Dumas' },
      { _id: '224', name: 'The Three Musketeers by Alexandre Dumas' },
      { _id: '225', name: 'Dracula by Bram Stoker' },
      { _id: '226', name: 'Frankenstein by Mary Shelley' },
      { _id: '227', name: 'The Odyssey by Homer' },
      { _id: '228', name: 'The Iliad by Homer' },
      { _id: '229', name: 'The Divine Comedy by Dante Alighieri' },
      { _id: '230', name: 'The Aeneid by Virgil' },
      { _id: '231', name: 'The Metamorphosis by Franz Kafka' },
      { _id: '232', name: 'The Trial by Franz Kafka' },
      { _id: '233', name: 'The Stranger by Albert Camus' },
      { _id: '234', name: 'The Plague by Albert Camus' },
      { _id: '235', name: 'The Old Man and the Sea by Ernest Hemingway' },
      { _id: '236', name: 'For Whom the Bell Tolls by Ernest Hemingway' },
      { _id: '237', name: 'A Farewell to Arms by Ernest Hemingway' },
      { _id: '238', name: 'The Sun Also Rises by Ernest Hemingway' },
      { _id: '239', name: 'The Sound and the Fury by William Faulkner' },
      { _id: '240', name: 'As I Lay Dying by William Faulkner' },
      { _id: '241', name: 'The Grapes of Wrath by John Steinbeck' },
      { _id: '242', name: 'East of Eden by John Steinbeck' },
      { _id: '243', name: 'Of Mice and Men by John Steinbeck' },
      { _id: '244', name: 'The Pearl by John Steinbeck' },
      { _id: '245', name: 'The Scarlet Letter by Nathaniel Hawthorne' },
      { _id: '246', name: 'Moby Dick by Herman Melville' },
      { _id: '247', name: 'The Call of the Wild by Jack London' },
      { _id: '248', name: 'White Fang by Jack London' },
      { _id: '249', name: 'The Jungle Book by Rudyard Kipling' },
      { _id: '250', name: 'Kim by Rudyard Kipling' },
      { _id: '251', name: 'The Catcher in the Rye by J.D. Salinger' },
      { _id: '252', name: 'The Great Gatsby by F. Scott Fitzgerald' },
      { _id: '253', name: 'Tender is the Night by F. Scott Fitzgerald' },
      { _id: '254', name: 'This Side of Paradise by F. Scott Fitzgerald' },
      { _id: '255', name: 'The Beautiful and Damned by F. Scott Fitzgerald' },
      { _id: '256', name: 'The Bell Jar by Sylvia Plath' },
      { _id: '257', name: "The Handmaid's Tale by Margaret Atwood" },
      { _id: '258', name: 'The Road by Cormac McCarthy' },
      { _id: '259', name: 'Blood Meridian by Cormac McCarthy' },
      { _id: '260', name: 'No Country for Old Men by Cormac McCarthy' },
      { _id: '261', name: 'The Catch-22 by Joseph Heller' },
      { _id: '262', name: 'Slaughterhouse-Five by Kurt Vonnegut' },
      { _id: '263', name: "Cat's Cradle by Kurt Vonnegut" },
      { _id: '264', name: 'Breakfast of Champions by Kurt Vonnegut' },
      { _id: '265', name: 'The Sirens of Titan by Kurt Vonnegut' },
      {
        _id: '266',
        name: "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
      },
      { _id: '267', name: 'Dune by Frank Herbert' },
      { _id: '268', name: 'Foundation by Isaac Asimov' },
      { _id: '269', name: 'Neuromancer by William Gibson' },
      { _id: '270', name: 'Snow Crash by Neal Stephenson' },
      { _id: '271', name: 'The Left Hand of Darkness by Ursula K. Le Guin' },
      { _id: '272', name: 'The Dispossessed by Ursula K. Le Guin' },
      { _id: '273', name: 'The Lathe of Heaven by Ursula K. Le Guin' },
      { _id: '274', name: 'The Wind-Up Bird Chronicle by Haruki Murakami' },
      { _id: '275', name: 'Norwegian Wood by Haruki Murakami' },
      { _id: '276', name: 'Kafka on the Shore by Haruki Murakami' },
      { _id: '277', name: '1Q84 by Haruki Murakami' },
      { _id: '278', name: 'The Catcher in the Rye by J.D. Salinger' },
      { _id: '279', name: 'The Great Gatsby by F. Scott Fitzgerald' },
      { _id: '280', name: 'Tender is the Night by F. Scott Fitzgerald' },
      { _id: '281', name: 'This Side of Paradise by F. Scott Fitzgerald' },
      { _id: '282', name: 'The Beautiful and Damned by F. Scott Fitzgerald' },
      { _id: '283', name: 'The Bell Jar by Sylvia Plath' },
      { _id: '284', name: "The Handmaid's Tale by Margaret Atwood" },
      { _id: '285', name: 'The Road by Cormac McCarthy' },
      { _id: '286', name: 'Blood Meridian by Cormac McCarthy' },
      { _id: '287', name: 'No Country for Old Men by Cormac McCarthy' },
      { _id: '288', name: 'The Catch-22 by Joseph Heller' },
      { _id: '289', name: 'Slaughterhouse-Five by Kurt Vonnegut' },
      { _id: '290', name: "Cat's Cradle by Kurt Vonnegut" },
      { _id: '291', name: 'Breakfast of Champions by Kurt Vonnegut' },
      { _id: '292', name: 'The Sirens of Titan by Kurt Vonnegut' },
      {
        _id: '293',
        name: "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
      },
      { _id: '294', name: 'Dune by Frank Herbert' },
      { _id: '295', name: 'Foundation by Isaac Asimov' },
      { _id: '296', name: 'Neuromancer by William Gibson' },
      { _id: '297', name: 'Snow Crash by Neal Stephenson' },
      { _id: '298', name: 'The Left Hand of Darkness by Ursula K. Le Guin' },
      { _id: '299', name: 'The Dispossessed by Ursula K. Le Guin' },
      { _id: '300', name: 'The Lathe of Heaven by Ursula K. Le Guin' },
    ],
  },
  {
    _id: 'games',
    name: 'Games',
    activities: [
      { _id: '301', name: 'The Legend of Zelda: Breath of the Wild' },
      { _id: '302', name: 'The Witcher 3: Wild Hunt' },
      { _id: '303', name: 'Red Dead Redemption 2' },
      { _id: '304', name: 'Minecraft' },
      { _id: '305', name: 'Dark Souls III' },
      { _id: '306', name: 'Super Mario Odyssey' },
      { _id: '307', name: 'Overwatch' },
      { _id: '308', name: 'Fortnite' },
      { _id: '309', name: 'Cyberpunk 2077' },
      { _id: '310', name: 'Animal Crossing: New Horizons' },
      { _id: '311', name: 'God of War' },
      { _id: '312', name: 'Horizon Zero Dawn' },
      { _id: '313', name: 'Persona 5' },
      { _id: '314', name: 'Bloodborne' },
      { _id: '315', name: 'Sekiro: Shadows Die Twice' },
      { _id: '316', name: 'Final Fantasy VII Remake' },
      { _id: '317', name: 'Resident Evil 2' },
      { _id: '318', name: 'The Last of Us Part II' },
      { _id: '319', name: 'Ghost of Tsushima' },
      { _id: '320', name: 'Doom Eternal' },
      { _id: '321', name: 'Assassin’s Creed Valhalla' },
      { _id: '322', name: 'Call of Duty: Modern Warfare' },
      { _id: '323', name: 'Apex Legends' },
      { _id: '324', name: 'Valorant' },
      { _id: '325', name: 'League of Legends' },
      { _id: '326', name: 'Dota 2' },
      { _id: '327', name: 'Counter-Strike: Global Offensive' },
      { _id: '328', name: 'World of Warcraft' },
      { _id: '329', name: 'Genshin Impact' },
      { _id: '330', name: 'Among Us' },
      { _id: '331', name: 'Fall Guys' },
      { _id: '332', name: 'Rocket League' },
      { _id: '333', name: 'Stardew Valley' },
      { _id: '334', name: 'Terraria' },
      { _id: '335', name: 'Hades' },
      { _id: '336', name: 'Celeste' },
      { _id: '337', name: 'Hollow Knight' },
      { _id: '338', name: 'Cuphead' },
      { _id: '339', name: 'Ori and the Will of the Wisps' },
      { _id: '340', name: 'Monster Hunter: World' },
      { _id: '341', name: 'The Elder Scrolls V: Skyrim' },
      { _id: '342', name: 'Grand Theft Auto V' },
      { _id: '343', name: 'Metal Gear Solid V: The Phantom Pain' },
      { _id: '344', name: 'Batman: Arkham Knight' },
      { _id: '345', name: 'Uncharted 4: A Thief’s End' },
      { _id: '346', name: 'Spider-Man' },
      { _id: '347', name: 'Control' },
      { _id: '348', name: 'Death Stranding' },
      { _id: '349', name: 'Nier: Automata' },
      { _id: '350', name: 'The Outer Worlds' },
      { _id: '351', name: 'Divinity: Original Sin 2' },
      { _id: '352', name: 'Pillars of Eternity II: Deadfire' },
      { _id: '353', name: 'Disco Elysium' },
      { _id: '354', name: 'The Banner Saga' },
      { _id: '355', name: 'XCOM 2' },
      { _id: '356', name: 'Civilization VI' },
      { _id: '357', name: 'Total War: Three Kingdoms' },
      { _id: '358', name: 'Crusader Kings III' },
      { _id: '359', name: 'Factorio' },
      { _id: '360', name: 'Cities: Skylines' },
      { _id: '361', name: 'Planet Coaster' },
      { _id: '362', name: 'Kerbal Space Program' },
      { _id: '363', name: 'Subnautica' },
      { _id: '364', name: 'The Sims 4' },
      { _id: '365', name: 'RimWorld' },
      { _id: '366', name: 'Prison Architect' },
      { _id: '367', name: 'Frostpunk' },
      { _id: '368', name: 'Surviving Mars' },
      { _id: '369', name: 'Anno 1800' },
      { _id: '370', name: 'Tropico 6' },
      { _id: '371', name: 'Banished' },
      { _id: '372', name: 'Oxygen Not Included' },
      { _id: '373', name: 'Slay the Spire' },
      { _id: '374', name: 'Darkest Dungeon' },
      { _id: '375', name: 'Into the Breach' },
      { _id: '376', name: 'FTL: Faster Than Light' },
      { _id: '377', name: 'Dead Cells' },
      { _id: '378', name: 'Risk of Rain 2' },
      { _id: '379', name: 'Enter the Gungeon' },
      { _id: '380', name: 'Spelunky 2' },
      { _id: '381', name: 'Rogue Legacy 2' },
      { _id: '382', name: 'Hades' },
      { _id: '383', name: 'Celeste' },
      { _id: '384', name: 'Hollow Knight' },
      { _id: '385', name: 'Cuphead' },
      { _id: '386', name: 'Ori and the Will of the Wisps' },
      { _id: '387', name: 'Monster Hunter: World' },
      { _id: '388', name: 'The Elder Scrolls V: Skyrim' },
      { _id: '389', name: 'Grand Theft Auto V' },
      { _id: '390', name: 'Metal Gear Solid V: The Phantom Pain' },
      { _id: '391', name: 'Batman: Arkham Knight' },
      { _id: '392', name: 'Uncharted 4: A Thief’s End' },
      { _id: '393', name: 'Spider-Man' },
      { _id: '394', name: 'Control' },
      { _id: '395', name: 'Death Stranding' },
      { _id: '396', name: 'Nier: Automata' },
      { _id: '397', name: 'The Outer Worlds' },
      { _id: '398', name: 'Divinity: Original Sin 2' },
      { _id: '399', name: 'Pillars of Eternity II: Deadfire' },
      { _id: '400', name: 'Disco Elysium' },
    ],
  },
  {
    _id: 'useful_activities',
    name: 'Useful Activities',
    activities: [
      { _id: '1', name: 'Reading popular science books' },
      { _id: '2', name: 'Participating in online courses (Coursera, Udemy)' },
      { _id: '3', name: 'Practicing yoga or meditation' },
      { _id: '4', name: 'Learning a new language' },
      { _id: '5', name: 'Planning a personal budget' },
      { _id: '6', name: 'Cleaning and organizing the house' },
      { _id: '7', name: 'Cooking: trying a new recipe' },
      { _id: '8', name: 'Gardening or caring for plants' },
      { _id: '9', name: 'Updating resume and portfolio' },
      { _id: '10', name: 'Practicing time management' },
      { _id: '11', name: 'Walking outdoors in fresh air' },
      { _id: '12', name: 'Conducting a digital detox' },
      { _id: '13', name: 'Listening to podcasts on interesting topics' },
      { _id: '14', name: 'Repairing small household appliances' },
      { _id: '15', name: 'Volunteering or helping charity projects' },
      { _id: '16', name: 'Learning photography' },
      { _id: '17', name: 'Exercising at home or the gym' },
      { _id: '18', name: 'Writing a journal or personal notes' },
      { _id: '19', name: 'Learning the basics of programming' },
      { _id: '20', name: 'Studying the history or culture of another nation' },
      { _id: '21', name: 'Watching educational documentaries' },
      { _id: '22', name: 'Developing a personal project or blog' },
      { _id: '23', name: 'Learning basic first aid skills' },
      { _id: '24', name: 'Exploring arts: drawing, music, sculpture' },
      { _id: '25', name: 'Reading biographies of remarkable people' },
      { _id: '26', name: 'Practicing mindfulness' },
      { _id: '27', name: 'Participating in local community events' },
      { _id: '28', name: 'Working on personal discipline' },
      { _id: '29', name: 'Redesigning home interior' },
      { _id: '30', name: 'Spending family time with board games' },
    ],
  },
  {
    _id: 'cultural_activities',
    name: 'Cultural Activities',
    activities: [
      { _id: '1', name: 'Visiting a museum' },
      { _id: '2', name: 'Attending a theater performance' },
      { _id: '3', name: 'Participating in a festival or fair' },
      { _id: '4', name: 'Watching an opera or ballet' },
      { _id: '5', name: 'Visiting a contemporary art gallery' },
      { _id: '6', name: 'Touring historical city landmarks' },
      { _id: '7', name: 'Public poetry or prose reading' },
      { _id: '8', name: 'Exploring traditional cuisines of different nations' },
      { _id: '9', name: 'Watching national or classic films' },
      { _id: '10', name: 'Going to a planetarium or observatory' },
      { _id: '11', name: 'Taking part in a craft or art workshop' },
      { _id: '12', name: 'Attending a music concert' },
      { _id: '13', name: 'Celebrating a national or cultural holiday' },
      { _id: '14', name: 'Visiting religious monuments and temples' },
      { _id: '15', name: 'Joining a book club' },
      { _id: '16', name: 'Discussing art with friends or acquaintances' },
      { _id: '17', name: 'Spending an evening listening to classical music' },
      { _id: '18', name: 'Creating your own piece of art' },
      { _id: '19', name: 'Attending a dance performance' },
      { _id: '20', name: 'Going to a lecture or public talk' },
      { _id: '21', name: 'Exploring foreign cultures through literature' },
      { _id: '22', name: 'Learning about folklore and legends' },
      { _id: '23', name: 'Visiting a photo gallery or exhibition' },
      { _id: '24', name: 'Discussing films or books in a discussion club' },
      { _id: '25', name: 'Watching a documentary about culture' },
      { _id: '26', name: 'Hosting a themed evening at home' },
      { _id: '27', name: 'Participating in amateur theater' },
      { _id: '28', name: 'Touring a science and technology museum' },
      {
        _id: '29',
        name: 'Learning about the cultural heritage of your region',
      },
      { _id: '30', name: 'Practicing traditional dances' },
    ],
  },
  {
    _id: 'sports_activities',
    name: 'Sports Activities',
    activities: [
      { _id: '1', name: 'Jogging in the park' },
      { _id: '2', name: 'Cycling' },
      { _id: '3', name: 'Playing football' },
      { _id: '4', name: 'Practicing yoga' },
      { _id: '5', name: 'Gym workout' },
      { _id: '6', name: 'Playing basketball' },
      { _id: '7', name: 'Roller skating' },
      { _id: '8', name: 'Swimming in the pool' },
      { _id: '9', name: 'Rock climbing' },
      { _id: '10', name: 'Long-distance walking' },
      { _id: '11', name: 'Playing tennis' },
      { _id: '12', name: 'Snowboarding' },
      { _id: '13', name: 'Skiing' },
      { _id: '14', name: 'Group cycling training' },
      { _id: '15', name: 'Playing volleyball' },
      { _id: '16', name: 'Martial arts' },
      { _id: '17', name: 'Trampoline jumping' },
      { _id: '18', name: 'Rowing' },
      { _id: '19', name: 'Dancing' },
      { _id: '20', name: 'Ice skating' },
      { _id: '21', name: 'Practicing pilates' },
      { _id: '22', name: 'Crossfit training' },
      { _id: '23', name: 'Playing golf' },
      { _id: '24', name: 'Fencing' },
      { _id: '25', name: 'Kitesurfing' },
      { _id: '26', name: 'Aquafitness workouts' },
      { _id: '27', name: 'Outdoor yoga' },
      { _id: '28', name: 'Playing table tennis' },
      { _id: '29', name: 'Practicing Zumba' },
      { _id: '30', name: 'Morning exercises' },
    ],
  },
  {
    _id: 'creative_activities',
    name: 'Creative Activities',
    activities: [
      { _id: '1', name: 'Drawing with pencils or paints' },
      { _id: '2', name: 'Writing stories or poems' },
      { _id: '3', name: 'Photography and photo editing' },
      { _id: '4', name: 'Creating sketches or comics' },
      { _id: '5', name: 'Playing a musical instrument' },
      { _id: '6', name: 'Sculpting or clay modeling' },
      { _id: '7', name: 'Sewing clothes or accessories' },
      { _id: '8', name: 'Decorating interiors' },
      { _id: '9', name: 'Learning calligraphy' },
      { _id: '10', name: 'Keeping a journal with illustrations' },
      { _id: '11', name: 'Making bracelets or macramé' },
      { _id: '12', name: 'Creating digital art' },
      { _id: '13', name: 'Making handmade greeting cards' },
      { _id: '14', name: 'Learning dance moves' },
      { _id: '15', name: 'Making decorative candles' },
      { _id: '16', name: 'Scrapbooking' },
      { _id: '17', name: 'Making beaded jewelry' },
      { _id: '18', name: 'Editing and creating videos' },
      { _id: '19', name: 'Blogging' },
      { _id: '20', name: 'Furniture restoration' },
      { _id: '21', name: 'Digital drawing' },
      { _id: '22', name: 'Singing or recording vocals' },
      { _id: '23', name: 'Creating your own recipes' },
      { _id: '24', name: 'Gardening and plant care' },
      { _id: '25', name: 'Writing scripts or plays' },
      { _id: '26', name: 'Designing board games' },
      { _id: '27', name: 'Composing melodies or electronic tracks' },
      { _id: '28', name: 'Culinary decoration' },
      { _id: '29', name: 'Creating costumes or cosplay' },
      { _id: '30', name: 'Learning acting techniques' },
    ],
  },
  {
    _id: 'intellectual_activities',
    name: 'Intellectual Activities',
    activities: [
      { _id: '1', name: 'Solving crosswords' },
      { _id: '2', name: 'Learning a new language' },
      { _id: '3', name: 'Playing chess' },
      { _id: '4', name: 'Studying a new scientific topic' },
      { _id: '5', name: 'Reading scientific articles' },
      { _id: '6', name: 'Solving puzzles' },
      { _id: '7', name: 'Learning programming' },
      { _id: '8', name: 'Watching lectures or courses' },
      { _id: '9', name: 'Planning personal goals' },
      { _id: '10', name: 'Learning financial literacy' },
      { _id: '11', name: 'Solving math problems' },
      { _id: '12', name: 'Playing intellectual board games' },
      { _id: '13', name: 'Writing essays on free topics' },
      { _id: '14', name: 'Studying history' },
      { _id: '15', name: 'Exploring philosophical concepts' },
      { _id: '16', name: 'Learning astronomy' },
      { _id: '17', name: 'Studying neuroscience' },
      { _id: '18', name: 'Analyzing world news' },
      { _id: '19', name: 'Learning negotiation skills' },
      { _id: '20', name: 'Creating a personal development strategy' },
      { _id: '21', name: 'Practicing concentration meditation' },
      { _id: '22', name: 'Speed reading practice' },
      { _id: '23', name: 'Solving logical problems' },
      { _id: '24', name: 'Analyzing classic literature' },
      { _id: '25', name: 'Playing Go' },
      { _id: '26', name: 'Creating mind maps' },
      { _id: '27', name: 'Memory training' },
      { _id: '28', name: 'Studying ecology' },
      { _id: '29', name: 'Writing analytical notes' },
      { _id: '30', name: 'Participating in trivia quizzes' },
    ],
  },
  {
    _id: 'social_activities',
    name: 'Social Activities',
    activities: [
      { _id: '1', name: 'Attending friend gatherings' },
      { _id: '2', name: 'Hosting a board game night' },
      { _id: '3', name: 'Volunteering at events' },
      { _id: '4', name: 'Having coffee with colleagues' },
      { _id: '5', name: 'Meeting new people at events' },
      { _id: '6', name: 'Visiting relatives' },
      { _id: '7', name: 'Joining culinary workshops' },
      { _id: '8', name: 'Attending dance parties' },
      { _id: '9', name: 'Watching a movie together' },
      { _id: '10', name: 'Organizing a picnic outdoors' },
      { _id: '11', name: 'Playing team sports' },
      { _id: '12', name: 'Joining interest clubs' },
      { _id: '13', name: 'Participating in discussion groups' },
      { _id: '14', name: 'Book club meetings' },
      { _id: '15', name: 'Organizing photo shoots with friends' },
      { _id: '16', name: 'Participating in charity events' },
      { _id: '17', name: 'Attending concerts' },
      { _id: '18', name: 'Going to escape rooms' },
      { _id: '19', name: 'Hosting a barbecue' },
      { _id: '20', name: 'Learning a new skill together' },
      { _id: '21', name: 'Visiting exhibitions and museums' },
      { _id: '22', name: 'Karaoke nights' },
      { _id: '23', name: 'Joining training sessions or seminars' },
      { _id: '24', name: 'Organizing a culinary marathon' },
      { _id: '25', name: 'Group outings to theater or cinema' },
      { _id: '26', name: 'Playing trivia games' },
      { _id: '27', name: 'Attending themed parties' },
      { _id: '28', name: 'Taking group trips out of town' },
      { _id: '29', name: 'Cooking together' },
      { _id: '30', name: 'Practicing in language clubs' },
    ],
  },
];
